# -*- coding: utf-8 -*-
"""SSSafety.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyIkz1W5dg1N4zUVgWl-mmMAsZeN3yJa

# [**Space Station Safety Object Detecion**](https://)

**Installing important libraries**
"""

!pip install ultralytics
from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

"""**Importing yolo and Downloading medium size model**"""

import ultralytics
from ultralytics import YOLO
model = YOLO("yolov8m.pt")

"""**Setting the Dataset path**"""

dataset_path = "/content/drive/MyDrive/AugData"

"""**Training code with data augmentation**"""

model.train(
    data='/content/drive/MyDrive/AugData/yolo.yaml',
    epochs=100,imgsz=640,batch=8,
    optimizer='AdamW',
    cos_lr=True,
    lr0=0.002,
    lrf=0.01,
    momentum=0.9,
    weight_decay=0.0005,
    patience=60,
    cache='disk',
    deterministic=True,
    exist_ok=True,
    augment=True,
    hsv_h=0.02,
    hsv_s=0.8,
    hsv_v=0.6,
    translate=0.2,
    scale=0.7,
    degrees=15,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.1,
    close_mosaic=10,
    erasing=0.4,
    auto_augment='randaugment',
    overlap_mask=True,
    verbose=True,
    plots=True,
    project='/content/drive/MyDrive/AugData/Results',
    name='YOLOv8m_Final'
)

"""*Resuming the model train from 20th epoch*"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/AugData/Results/YOLOv8m_Final/weights/last.pt')

model.train(
    data='/content/drive/MyDrive/AugData/yolo.yaml',
    epochs=100,                # total target; YOLO auto-resumes at 20/100
    resume=True,
)

"""*Resuming the model training from 69th epoch*"""

model = YOLO('/content/drive/MyDrive/AugData/Results/YOLOv8m_Final/weights/last.pt')

model.train(
    data='/content/drive/MyDrive/AugData/yolo.yaml',
    epochs=100,          # total target, not +31
    resume=True,         # continues from 69/100 automatically
    save_period=5,       # save every 5 epochs to protect progress
)

"""**Listing the results folder**"""

!ls '/content/drive/MyDrive/AugData/Results/YOLOv8m_Final'

"""**Presenting the Confusion Matrix**"""

from IPython.display import Image,display
resultData=('/content/drive/MyDrive/AugData/Results/YOLOv8m_Final')
Image(filename=f'{resultData}/confusion_matrix.png')

"""**Presenting Results data**"""

resultData=('/content/drive/MyDrive/AugData/Results/YOLOv8m_Final')
Image(filename=f'{resultData}/results.png')

"""**Results of 5 heads**"""

import pandas as pd
resultData = '/content/drive/MyDrive/AugData/Results/YOLOv8m_Final/'
df = pd.read_csv(f'{resultData}results.csv')
print(df.head(5))

"""**Results of a tail**"""

import pandas as pd
df=pd.read_csv(f'{resultData}results.csv')
print(df.tail(1))

"""**Validating the model on the test dataset**"""

model.val(
    data='/content/drive/MyDrive/AugData/yolo.yaml',
    split='test',
    save_json=True,
    conf=0.25
)

"""**Running predictions on the test dataset**"""

results = model.predict(source='/content/drive/MyDrive/AugData/SSTest.v2i.yolov8/test/images', conf=0.25, save=True)

"""**Displaying 10 predicted images**"""

import os
from IPython.display import Image, display

predict_dir = '/content/drive/MyDrive/YOLO_Predictions'
image_files = [f for f in os.listdir(predict_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

image_files.sort()

print(f"Found {len(image_files)} predicted images. Displaying the first 10:")

for i, image_file in enumerate(image_files[:10]):
    print(f"Displaying image {i+1}: {image_file}")
    display(Image(filename=os.path.join(predict_dir, image_file)))

"""**Zipping the predicted data**"""

!zip -r /content/predict.zip /content/runs/detect/predict

"""**Downloading the predict file on local machine**"""

from google.colab import files
files.download("/content/predict.zip")

"""**Downloading the predicted data to google drive**"""

!cp -r /content/runs/detect/predict /content/drive/MyDrive/YOLO_Predictions

"""**Zips the val data**"""

!zip -r /content/val.zip /content/runs/detect/val

"""**Download the val data on local machine**"""

from google.colab import files
files.download("/content/val.zip")

"""**Downloads the vala data on google drive**"""

!cp -r /content/runs/detect/val /content/drive/MyDrive/YOLO_Val